In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#Import the libraries
import zipfile
import os
import tensorflow as tf
import matplotlib. pyplot as plt.
import matplotlib. image as mpimg.

zip_ref = zipfile.ZipFile('/content/drive/MyDrive/train.zip', 'r') #Opens the zip file in read mode
zip_ref.extractall('/content/tmp') #Extracts the files into the /tmp folder
zip_ref.close()
print(len(os.listdir('/content/tmp/train')))

2001


In [ ]:
import os
import cv2
# IMG_SHAPE = 256
# BATCH_SIZE = 32
mylist = os.listdir('/content/tmp/train')
#print(mylist)
print(len(mylist))
train = []
test = []
# train_dir = '/tmp/train/'
# train_data = tf.keras.utils.image_dataset_from_directory(train_dir, 
#                                                          labels = "inferred", 
#                                                          color_mode='rgb', 
#                                                          batch_size=BATCH_SIZE, 
#           
c=0;                                               #image_size=(IMG_SHAPE, IMG_SHAPE))
for i in mylist:
  if c<1800:
    train.append(i)
  else:
    test.append(i)
  c=c+1

print(len(train))
print(len(test))
hsv_train=[]
myrootPath = "/content/tmp/train"
for filename in train:
    path = os.path.join(myrootPath,filename)
    bgr_img = cv2.imread(path)
    if bgr_img is not None:
      hsv_train.append(cv2.cvtColor(bgr_img, cv2.COLOR_BGR2HSV))

print(len(hsv_train))
print(hsv_train[0])

2001
1800
201
1799


In [ ]:
print(hsv_train[0])
imgplot = plt. imshow(hsv_train[0])

[[[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 ...

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]]


In [ ]:
myrootPath = "/content/tmp/train"
print(hsv_train[0])
path_=os.path.join(myrootPath,hsv_train[0])
img = mpimg. imread(path_)

[[[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 ...

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]

 [[108  76 255]
  [108  76 255]
  [108  76 255]
  ...
  [108  76 255]
  [108  76 255]
  [108  76 255]]]


TypeError: ignored

In [ ]:
path

'/content/tmp/train/476.png'

In [ ]:
bgr_img = cv2.imread(path)

In [ ]:
bgr_img

array([[[255, 209, 179],
        [255, 209, 179],
        [255, 209, 179],
        ...,
        [255, 209, 179],
        [255, 209, 179],
        [255, 209, 179]],

       [[255, 209, 179],
        [255, 209, 179],
        [255, 209, 179],
        ...,
        [255, 209, 179],
        [255, 209, 179],
        [255, 209, 179]],

       [[255, 209, 179],
        [255, 209, 179],
        [255, 209, 179],
        ...,
        [255, 209, 179],
        [255, 209, 179],
        [255, 209, 179]],

       ...,

       [[255, 209, 179],
        [255, 209, 179],
        [255, 209, 179],
        ...,
        [255, 209, 179],
        [255, 209, 179],
        [255, 209, 179]],

       [[255, 209, 179],
        [255, 209, 179],
        [255, 209, 179],
        ...,
        [255, 209, 179],
        [255, 209, 179],
        [255, 209, 179]],

       [[255, 209, 179],
        [255, 209, 179],
        [255, 209, 179],
        ...,
        [255, 209, 179],
        [255, 209, 179],
        [255, 209, 179]]